# Celebration colour theme
# Frank Leigh

# Constants
"constant" = "#bebebe" 
"constant.builtin" = "#bebebe"
"constant.builtin.boolean" = "#bebebe"
"constant.builtin.character" = "#bebebe"
"constant.character.escape" = "#bebebe"
"constant.macro" = "#bebebe"
"constant.numeric" = "#bebebe"
"constructor" = "#bebebe"

# Diagnostics
"diagnostic" = { underline = { color = "#bebebe", style = "curl" } }
"diagnostic.error" = { underline = { color = "#bebebe", style = "curl" } }
"error" = "#ff0000ยง"
"diagnostic.hint" = { underline = { color = "#bebebe", style = "curl" } }
"hint" = "#bebebe"
"diagnostic.info" = { underline = { color = "#bebebe", style = "curl" } }
"info" = "#bebebe"
"diagnostic.warning" = { underline = { color = "#bebebe", style = "curl" } }
"warning" = "#bebebe"
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

# Diffs
"diff.delta" = "#bebebe"
"diff.minus" = "#bebebe"
"diff.plus" = "#bebebe"

# Functions
"function" = "#ff645e"
"function.builtin" = "#bebebe"
"function.method" = "#ff645e"
"function.macro" = "#ffffff"
"function.special" = "#ffffff"

# Git
"git.delta.moved" = "#bebebe"

# Keywords
"keyword" = "#fce231"
"keyword.control.conditional" = "#fce231"
"keyword.control.exception" = "#fce231"
"keyword.control.repeat" = "#fce231"
"keyword.directive" = "yellow"
"keyword.function" = "#ff645e"
"keyword.operator" = "#fce231"
"keyword.return" = "#bebebe"
"keyword.storage.modifier" = "#bebebe"
"keyword.storage.type" = "#fce231"

# Punctuation
"punctuation" = "#bebebe"
"punctuation.bracket" = "#bebebe"
"punctuation.delimiter" = "#bebebe"
"punctuation.special" = "#bebebe"

# Strings
"string" = "#32d924"
"string.escape" = "#bebebe"
"string.regex" = "#bebebe"
"string.special" = "yellow"

# Types
"type" = "#56abff"
"type.builtin" = "#bebebe"

# Variables
"variable" = "#c7c7c7"
"variable.builtin" = "#bebebe"
"variable.other.member" = "#bebebe"
"variable.parameter" = "#bebebe"
"attribute" = "#c8c8ff"

# Misc
"label" = "#bebebe"
"namespace" = "#b2b2b3"
"operator" = "#c4c4c4"
"special" = "#bebebe"
"tag" = "#56abff"
"comment" = { fg = "#777777", modifiers = ["italic"] }

## EDITOR UI COLORS

# "ui.background" = { bg = "#222F3E" }
"ui.text" = "#bebebe"
"ui.window" = "#bebebe"

# Debug
"ui.debug.active" = "#bebebe"
"ui.debug.breakpoint" = "#bebebe"

# Popus and menus
"ui.menu" = { bg = "#334b65" }
"ui.menu.scroll" = { fg = "#bebebe", bg = "#333333" }
"ui.menu.selected" = { fg = "#bebebe", bg = "#333333" }
"ui.popup" = { bg = "#000000" }
"ui.popup.info" = { bg = "grey" }
"ui.help" = { bg = "#1c3c56" }
"ui.text.focus" = { fg = "#bebebe", bg = "#333333" }

# Gutter
"ui.gutter" = "#767ba5"
"ui.linenr" = "#888888"
"ui.linenr.selected" = "#cccccc"

# Cursor
"ui.cursor" = { fg = "#d8dee9", modifiers = [ "reversed" ] }
"ui.cursorcolumn.primary" = { bg = "#3B4252" }

"ui.selection" = { bg = "#505050" }
"ui.highlight" = { bg = "#444444" }

# Statusline
"ui.statusline" = {  bg = "#384a63" }
"ui.statusline.inactive" = { fg = "#bebebe", bg = "#333333" }
"ui.statusline.insert" = { fg = "#bebebe", bg = "#999999" }
"ui.statusline.normal" = { fg = "#bebebe", bg = "#999999" }
"ui.statusline.separator" = "#bebebe"

# Virtual/invisible text

# Bufferline
"ui.bufferline" = { fg = "#bebebe", bg = "#384a63" }
"ui.bufferline.active" = { fg = "#ffffff", bg = "#ff0000", underline = { color = "#333333", style = "line" }, modifiers = [ "italic" ] }

# Markup
"markup.heading" = "#bebebe"
"markup.list" = "#bebebe"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.text" = "#bebebe"
"markup.raw" = "#bebebe"
